"use client"

import { Eye, HeartHandshake, ShieldCheck, Sparkles, Users } from "lucide-react"
import { PageHero } from "@/components/page-hero"
import { useLanguage } from "@/components/language-provider"

const copy = {
  ms: { eyebrow: "Tentang Carwash Bossque", title: "Penjagaan kenderaan tempatan, dibuat dengan standard yang jelas", description: "Kami membantu pemandu di Padang Besar menjaga kenderaan mereka melalui servis yang mudah difahami, harga telus dan kerja yang teliti.", storyTitle: "Dibina untuk komuniti yang bergerak", story: "Carwash Bossque diwujudkan untuk menjadikan penjagaan kenderaan lebih ringkas bagi pemandu tempatan. Setiap kunjungan bermula dengan pilihan servis yang jelas dan berakhir dengan kemasan yang diperiksa dengan teliti.", missionTitle: "Misi kami", mission: "Memberikan pengalaman cucian kereta yang konsisten, mudah dan jujur—supaya setiap pelanggan boleh memandu keluar dengan lebih yakin.", teamTitle: "Pasukan di sebalik kilauan", teamIntro: "Operasi kami digerakkan oleh peranan yang saling melengkapi, dengan fokus yang sama pada kualiti dan layanan.", roles: ["Pakar cucian & kemasan", "Penjagaan ruang dalaman", "Sokongan pelanggan"] },
  en: { eyebrow: "About Carwash Bossque", title: "Local vehicle care, delivered to a clear standard", description: "We help drivers in Padang Besar care for their vehicles through easy-to-understand services, transparent pricing, and attentive work.", storyTitle: "Built for a community on the move", story: "Carwash Bossque was created to make vehicle care simpler for local drivers. Every visit begins with a clear service choice and ends with a finish that is checked with care.", missionTitle: "Our mission", mission: "To deliver a consistent, convenient, and honest car wash experience—so every customer can drive away with greater confidence.", teamTitle: "The team behind the shine", teamIntro: "Our operation is powered by complementary roles, all sharing the same focus on quality and service.", roles: ["Wash & finish specialists", "Interior care crew", "Customer support"] },
}

export default function AboutPage() {
  const { lang } = useLanguage()
  const c = copy[lang]
  const values = lang === "ms" ? [{ icon: ShieldCheck, title: "Konsisten", text: "Proses yang jelas untuk hasil yang boleh dipercayai." }, { icon: Eye, title: "Telus", text: "Pilihan servis dan harga yang mudah disemak." }, { icon: HeartHandshake, title: "Mesra", text: "Layanan tempatan yang menghormati masa anda." }] : [{ icon: ShieldCheck, title: "Consistent", text: "A clear process for a result you can trust." }, { icon: Eye, title: "Transparent", text: "Service choices and prices that are easy to review." }, { icon: HeartHandshake, title: "Approachable", text: "Local service that respects your time." }]

  return <><PageHero eyebrow={c.eyebrow} title={c.title} description={c.description} action={{ label: lang === "ms" ? "Terokai servis" : "Explore services", href: "/services" }} /><section className="bg-background py-16 md:py-24"><div className="mx-auto grid max-w-6xl gap-10 px-4 lg:grid-cols-2"><div className="flex flex-col gap-4"><Sparkles className="size-8 text-navy" /><h2 className="font-heading text-3xl font-bold text-balance">{c.storyTitle}</h2><p className="leading-relaxed text-muted-foreground">{c.story}</p></div><div className="rounded-3xl bg-navy p-8 text-white"><p className="text-sm font-bold uppercase tracking-wider text-lime">{c.missionTitle}</p><p className="mt-5 font-heading text-2xl font-bold leading-relaxed text-pretty">{c.mission}</p></div></div></section><section className="bg-muted py-16 md:py-24"><div className="mx-auto max-w-6xl px-4"><div className="mx-auto max-w-2xl text-center"><h2 className="font-heading text-3xl font-bold md:text-4xl">{lang === "ms" ? "Nilai yang memandu kerja kami" : "Values that guide our work"}</h2></div><ul className="mt-10 grid gap-6 md:grid-cols-3">{values.map(({ icon: Icon, title, text }) => <li key={title} className="rounded-2xl border border-border bg-card p-6"><span className="flex size-11 items-center justify-center rounded-xl bg-lime text-lime-foreground"><Icon className="size-5" /></span><h3 className="mt-5 font-heading text-xl font-bold">{title}</h3><p className="mt-2 leading-relaxed text-muted-foreground">{text}</p></li>)}</ul></div></section><section className="bg-background py-16 md:py-24"><div className="mx-auto max-w-6xl px-4"><div className="max-w-2xl"><Users className="size-8 text-navy" /><h2 className="mt-4 font-heading text-3xl font-bold">{c.teamTitle}</h2><p className="mt-3 leading-relaxed text-muted-foreground">{c.teamIntro}</p></div><ul className="mt-10 grid gap-4 md:grid-cols-3">{c.roles.map((role, index) => <li key={role} className="flex items-center gap-4 rounded-2xl border border-border p-5"><span className="font-heading text-2xl font-extrabold text-navy/30">0{index + 1}</span><span className="font-semibold">{role}</span></li>)}</ul></div></section></>
}
